-- Seed data for development
-- Default password for all seeded users: "password123"
-- bcrypt hash (cost 12) for "password123":
--   $2a$12$K1e5x8Xn7g5g5g5g5g5g5eN.Q7Y2i7Q7Y2i7Q7Y2i7Q7Y2i7Q7Y2i7
-- Replace with real hash generated by backend on first run if needed.

INSERT INTO departments (id, code, name_th, name_en) VALUES
    (gen_random_uuid(), 'ES',         'ฝ่ายวิศวกรรมระบบ',  'Engineering Services'),
    (gen_random_uuid(), 'ACCOUNTING', 'ฝ่ายบัญชี',           'Accounting'),
    (gen_random_uuid(), 'IT',         'ฝ่ายไอที',            'Information Technology')
ON CONFLICT (code) DO NOTHING;

INSERT INTO document_types (code, name, require_acknowledge, allowed_mime_types, max_file_size_mb) VALUES
    ('UAT',     'User Acceptance Test',   TRUE,  ARRAY['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'], 20),
    ('UAI',     'User Acceptance Install', TRUE, ARRAY['application/pdf'], 20),
    ('REPORT',  'General Report',          FALSE, ARRAY['application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], 20),
    ('INVOICE', 'Invoice',                 FALSE, ARRAY['application/pdf'], 10)
ON CONFLICT (code) DO NOTHING;
